apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - port: 3800
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: salvadorarmando/corecodebackend:0.2.0
          env:
            - name: POSTGRE_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: POSTGRE_HOST
              value: postgres
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 3800
