apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: init-db-config-map
          configMap:
            name: init-db
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
          resources:
            limits:
              memory: '256Mi'
              cpu: '500m'
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: init-db-config-map
              mountPath: /docker-entrypoint-initdb.d
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db
data:
  db.sql: |
    CREATE TABLE USERS (
      USER_ID text primary key,
      EMAIL text not null,
      DATE_ADDED date not null default CURRENT_TIMESTAMP
    );

    CREATE TABLE ACCOUNT_TYPE (
      ACCOUNT_TYPE_ID SERIAL primary key,
      DESCRIPTION text not null unique,
      DATE_ADDED date not null default CURRENT_TIMESTAMP
    );

    CREATE TABLE CURRENCY (
      CURRENCY_ID SERIAL primary key,
      DESCRIPTION text not null unique,
      DATE_ADDED date not null default CURRENT_TIMESTAMP
    );

    CREATE TABLE CATEGORY (
      CATEGORY_ID SERIAL primary key,
      DESCRIPTION text not null unique,
      DATE_ADDED date not null default CURRENT_TIMESTAMP
    );

    CREATE TABLE MOVEMENT (
      MOVEMENT_ID SERIAL primary key,
      DESCRIPTION text not null,
      DATE_ADDED date not null default CURRENT_TIMESTAMP
    );

    CREATE TABLE CURRENCY_RATE (
      CURRENCY_RATE_ID SERIAL primary key,
      CURRENCY_ID int not null references CURRENCY(CURRENCY_ID),
      CURRENCY_ID_TO int not null,
      RATE decimal not null,
      DATE_ADDED date not null default CURRENT_TIMESTAMP
    );

    CREATE TABLE ACCOUNT (
      ACCOUNT_ID SERIAL primary key,
      USER_ID text not null references USERS(USER_ID),
      DESCRIPTION text not null,
      BALANCE decimal not null,
      CURRENCY_ID int not null references CURRENCY(CURRENCY_ID),
      ACCOUNT_TYPE int not null references ACCOUNT_TYPE(ACCOUNT_TYPE_ID),
      DATE_ADDED date not null default CURRENT_TIMESTAMP
    );

    CREATE TABLE TRANSACTIONS (
      TRANSACTION_ID SERIAL primary key,
      USER_ID text not null references USERS(USER_ID),
      ACCOUNT_NUMBER_FROM int not null references ACCOUNT(ACCOUNT_ID),
      ACCOUNT_NUMBER_TO int,
      AMOUNT decimal not null,
      OWNER_TRANSACTION int not null,
      MOVEMENT_ID int not null references MOVEMENT(MOVEMENT_ID),
      CATEGORY_ID int not null references CATEGORY(CATEGORY_ID),
      DATE_ADDED date not null default CURRENT_TIMESTAMP
    );

    INSERT INTO CATEGORY (DESCRIPTION) VALUES ('COMIDA');
    INSERT INTO CATEGORY (DESCRIPTION) VALUES ('RENTA');
    INSERT INTO CATEGORY (DESCRIPTION) VALUES ('TRANSPORTE');
    INSERT INTO CATEGORY (DESCRIPTION) VALUES ('SALUD');
    INSERT INTO CATEGORY (DESCRIPTION) VALUES ('SALARIO');
    INSERT INTO CATEGORY (DESCRIPTION) VALUES ('REMESA');
    INSERT INTO CATEGORY (DESCRIPTION) VALUES ('TRANSFERENCIA');
    INSERT INTO CATEGORY (DESCRIPTION) VALUES ('DEPOSITO');

    INSERT INTO CURRENCY (DESCRIPTION) VALUES ('USD');
    INSERT INTO CURRENCY (DESCRIPTION) VALUES ('EUR');
    INSERT INTO CURRENCY (DESCRIPTION) VALUES ('GTQ');

    INSERT INTO ACCOUNT_TYPE (DESCRIPTION) VALUES ('AHORRO');
    INSERT INTO ACCOUNT_TYPE (DESCRIPTION) VALUES ('CORRIENTE');
    INSERT INTO ACCOUNT_TYPE (DESCRIPTION) VALUES ('EFECTIVO');

    INSERT INTO MOVEMENT (DESCRIPTION) VALUES ('INCOME');
    INSERT INTO MOVEMENT (DESCRIPTION) VALUES ('EXPENSE');

    INSERT INTO CURRENCY_RATE (CURRENCY_ID, CURRENCY_ID_TO, RATE) VALUES (2, 1, 1.15);
    INSERT INTO CURRENCY_RATE (CURRENCY_ID, CURRENCY_ID_TO, RATE) VALUES (1, 2, 0.87);
    INSERT INTO CURRENCY_RATE (CURRENCY_ID, CURRENCY_ID_TO, RATE) VALUES (1, 3, 7.73);
    INSERT INTO CURRENCY_RATE (CURRENCY_ID, CURRENCY_ID_TO, RATE) VALUES (3, 1, 0.13);
    INSERT INTO CURRENCY_RATE (CURRENCY_ID, CURRENCY_ID_TO, RATE) VALUES (2, 3, 8.85);
    INSERT INTO CURRENCY_RATE (CURRENCY_ID, CURRENCY_ID_TO, RATE) VALUES (3, 2, 0.11);
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
data:
  password: YWRtaW4=
type: Opaque
